packages:
  - climate-display
  - dashboard
  - family-chores
  - functions
  - health-tracker
  - kasa-controller
  - notes-app
  - tracker
  - packages/*

catalog:
  '@supabase/supabase-js': ^2.91.1
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-query': ^5.90.20
  '@types/node': ^24.0.0
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  concurrently: ^9.2.1
  date-fns: ^4.1.0
  lucide-react: ^0.563.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router-dom: ^7.13.0
  rollup-plugin-visualizer: ^6.0.5
  tailwindcss: ^4.1.18
  typescript: ~5.9.3
  vite: 8.0.0-beta.10
  vite-plugin-pwa: ^1.2.0
  zustand: ^5.0.10
